    // ============================================
    // TRANSLATION SYSTEM — 6 LANGUAGES
    // Default: French (fr)
    // ============================================
    const translations = {
  fr: {
    nav_artifacts: "Artéfacts",
    nav_bespoke: "Sur Mesure",
    nav_testimonials: "Témoignages",
    btn_join: "REJOINDRE",
    hero_headline: "Artéfacts Exclusifs pour les Élus",
    hero_subtext: "Accédez aux savoirs interdits, aux reliques sacrées et aux outils d'ascension. Réservé exclusivement à ceux qui cherchent la lumière au-delà du voile.",
    btn_explore: "Explorer les Artéfacts",
    btn_request: "Demander l'Initiation",
    trust_encrypted: "Chiffré",
    trust_members: "Membres",
    trust_countries: "Pays",
    trust_legacy: "Héritage",
    section_artifacts: "Artéfacts Sacrés",
    section_artifacts_desc: "Chaque pièce porte le poids des siècles. Façonnée par des maîtres, imprégnée de purpose.",
    filter_all: "Tous les Artéfacts",
    filter_jewelry: "Bijoux",
    filter_manuscripts: "Manuscrits",
    filter_tools: "Outils & Reliques",
    badge_limited: "Limité",
    badge_rare: "Rare",
    badge_bestseller: "Best-seller",
    badge_new: "Nouveau",
    badge_sacred: "Sacré",
    product1_name: "Le Pendentif Omniscient",
    product1_desc: "Pendentif omniscient en or 24 carats forgé à la main avec géométrie sacrée. Un bijou ésotérique porté par le cercle intérieur depuis le XVIIIe siècle pour la protection et l'éveil spirituel.",
    product2_name: "Grimoire de l'Illumination",
    product2_desc: "Grimoire de l'Illumination, manuscrit ancien relié en cuir véritable contenant 33 degrés de sagesse cachée. Chaque page est inscrite à la main pour les chercheurs de vérité occulte.",
    product3_name: "Anneau du Sceau de Pouvoir",
    product3_desc: "Anneau du Sceau de Pouvoir en obsidienne et émail cramoisi. Cette chevalière occulte canalise les énergies anciennes de l'Ordre et affirme l'autorité spirituelle de son porteur.",
    product4_name: "Bougie De Prière",
    product4_desc: "Bougie de prière rituelle en cire d'abeille pure avec mèche tressée. Conçue pour la méditation profonde, la purification de l'espace et l'élévation spirituelle lors des cérémonies sacrées.",
    product5_name: "Sceau de Salomon",
    product5_desc: "Sceau de Salomon authentique, livre d'impressions de sceaux en cire antique. Un grimoire de protection spirituelle contenant les sigils des 72 esprits de la hiérarchie.",
    product6_name: "Encens De Purification",
    product6_desc: "Encens de purification artisanal aux résines naturelles de myrrhe et d'oliban. Idéal pour le nettoyage énergétique, la protection de l'autel et l'harmonisation des vibrations lors des rituels.",
    btn_buy: "Acheter",
    section_testimonials: "Paroles de la Fraternité",
    testimonial1: '"Le pendentif a changé la trajectoire de ma vie. Des portes se sont ouvertes que je ne connaissais pas."',
    testimonial1_role: "33e Degré • Vérifié",
    testimonial2: '"Le Codex a révélé des vérités qu\'aucune université ne pouvait enseigner. Chaque centime de l\'investissement en valait la peine."',
    testimonial2_role: "Grand Maître • Vérifié",
    testimonial3: '"Je porte l\'Anneau du Sceau quotidiennement. Sa présence impose le respect dans chaque pièce où j\'entre."',
    testimonial3_role: "Cercle Intérieur • Vérifié",
    bespoke_badge: "Services Hors Marché",
    bespoke_title: "Artéfacts & Commissions Sur Mesure",
    bespoke_desc: "Pour ceux qui recherchent des pièces au-delà de notre catalogue. Nous travaillons avec un cercle restreint d'artisans maîtres pour créer des artéfacts personnalisés imprégnés de vos sigils et intentions.",
    bespoke1_title: "Regalia Personnalisé",
    bespoke1_desc: "Vêtements et regalia cérémoniels confectionnés selon vos spécifications exactes et votre degré.",
    bespoke2_title: "Grimoire Personnel",
    bespoke2_desc: "Livres des ombres écrits à la main, reliés de cuir fin avec votre nom en encre cramoisie.",
    bespoke3_title: "Talismans Uniques",
    bespoke3_desc: "Pièces uniques créées pour votre voyage d'illumination et de pouvoir.",
    btn_consultation: "Demander une Consultation",
    bespoke_note: "Notre concierge vous contactera sous 24 heures",
    guarantee_title: "Garantie du Serment Sacré",
    guarantee_desc: "Chaque artéfact est authentifié par le Grand Conseil. Si votre achat ne répond pas à vos attentes dans les 30 jours, nous honorons un remboursement complet — sans poser de questions. Votre confiance est notre alliance.",
    guarantee1: "Livraison Mondiale Gratuite",
    guarantee2: "Certificat d'Authenticité",
    guarantee3: "Emballage Discret",
    join_headline: "Accéder au Cercle Intérieur",
    join_subtext: "Ceux qui cherchent le pouvoir doivent prouver leur valeur. Rejoignez notre adhésion exclusive et accédez aux enchères restreintes, aux avant-premières VIP et aux cérémonies privées.",
    btn_bespoke: "Demander un Service Sur Mesure",
    modal_join_title: "Demander l'Initiation",
    modal_bespoke_title: "Consultation Sur Mesure",
    label_name: "Nom Complet",
    label_email: "Adresse Email",
    label_message: "Message",
    label_vision: "Votre Vision",
    btn_submit: "Soumettre",
    modal_join_note: "Votre candidature sera examinée par le Grand Conseil",
    modal_bespoke_note: "Nos artisans vous contacteront sous 48 heures",
    product7_name: "Baphomet Avec Installation",
    product7_desc: "Artefact rituel de Baphomet conçu pour l'installation sur autel. Forgé dans des métaux sacrés, cet objet d'invocation puissant est destiné aux praticiens avancés des arts occultes et des cérémonies de haute magie.",
    product8_name: "Carte De Tarot Illuminée",
    product8_desc: "Carte de tarot illuminée unique, ornée de dorures à la feuille d'or et de symboles ésotériques. Un outil de divination et de guidance spirituelle essentiel pour les lectures de tarot avancées.",
    product9_name: "Crâne de Cristal Clairvoyant",
    product9_desc: "Crâne de cristal clairvoyant sculpté dans du quartz pur de haute qualité. Un outil de méditation profonde qui amplifie la vision intérieure, la clairvoyance et la connexion aux plans supérieurs.",
    product10_name: "Calice du Graal",
    product10_desc: "Calice du Graal d'apparat en laiton doré avec gravures médiévales authentiques. Une relique sacrée utilisée dans les cérémonies les plus saintes et les rituels de communion spirituelle.",
    product11_name: "Parfums de Chance & D'Attirance",
    product11_desc: "Parfums de Chance & D'Attirance vintage, collection de fioles d'apothicaire en verre teinté à la main. Récipients parfaits pour conserver les élixirs, huiles essentielles et potions des anciens maîtres alchimistes.",
    product12_name: "Box D'invocation Baphomet",
    product12_desc: "Coffret d'invocation de Baphomet en bois sculpté et métal gravé. Cette boîte rituelle contient des sigils sacrés et des outils d'invocation pour les cérémonies occultes et la connexion aux énergies anciennes."
  },
  en: {
    nav_artifacts: "Artifacts",
    nav_bespoke: "Bespoke",
    nav_testimonials: "Testimonials",
    btn_join: "JOIN US",
    hero_headline: "Exclusive Artifacts for the Enlightened",
    hero_subtext: "Access forbidden knowledge, sacred relics, and tools of ascension. Reserved exclusively for those who seek the light beyond the veil.",
    btn_explore: "Explore Artifacts",
    btn_request: "Request Initiation",
    trust_encrypted: "Encrypted",
    trust_members: "Members",
    trust_countries: "Countries",
    trust_legacy: "Legacy",
    section_artifacts: "Sacred Artifacts",
    section_artifacts_desc: "Each piece carries the weight of centuries. Crafted by masters, imbued with purpose.",
    filter_all: "All Artifacts",
    filter_jewelry: "Jewelry",
    filter_manuscripts: "Manuscripts",
    filter_tools: "Tools & Relics",
    badge_limited: "Limited",
    badge_rare: "Rare",
    badge_bestseller: "Bestseller",
    badge_new: "New",
    badge_sacred: "Sacred",
    product1_name: "The All-Seeing Pendant",
    product1_desc: "Hand-forged 24k gold all-seeing pendant with sacred geometry. An esoteric jewel worn by the inner circle since the 18th century for protection and spiritual awakening.",
    product2_name: "Codex of Enlightenment",
    product2_desc: "Codex of Enlightenment, an ancient manuscript bound in genuine leather containing 33 degrees of hidden wisdom. Each page is hand-inscribed for seekers of occult truth.",
    product3_name: "Sigil of Power Ring",
    product3_desc: "Sigil of Power ring crafted from obsidian and crimson enamel. This occult signet channels the ancient energies of the Order and asserts the spiritual authority of its wearer.",
    product4_name: "Ritual Prayer Candle",
    product4_desc: "Ritual prayer candle made of pure beeswax with a braided wick. Designed for deep meditation, space purification, and spiritual elevation during sacred ceremonies.",
    product5_name: "Seal of Solomon",
    product5_desc: "Authentic Seal of Solomon, an antique wax seal impression book. A spiritual protection grimoire containing the sigils of the 72 spirits of the hierarchy.",
    product6_name: "Purification Incense",
    product6_desc: "Artisanal purification incense with natural myrrh and frankincense resins. Ideal for energy cleansing, altar protection, and harmonizing vibrations during rituals.",
    btn_buy: "Buy Now",
    section_testimonials: "Words from the Brotherhood",
    testimonial1: '"The pendant changed the trajectory of my life. Doors opened that I never knew existed."',
    testimonial1_role: "33rd Degree • Verified",
    testimonial2: '"The Codex revealed truths that no university could teach. Worth every cent of the investment."',
    testimonial2_role: "Grand Master • Verified",
    testimonial3: '"I wear the Sigil Ring daily. Its presence commands respect in every room I enter."',
    testimonial3_role: "Inner Circle • Verified",
    bespoke_badge: "Off-Market Services",
    bespoke_title: "Bespoke Artifacts & Commissions",
    bespoke_desc: "For those seeking items beyond our catalog. We work with a select circle of master craftsmen to create custom artifacts imbued with your personal sigils and intentions.",
    bespoke1_title: "Custom Regalia",
    bespoke1_desc: "Ceremonial garments and regalia crafted to your exact specifications and degree.",
    bespoke2_title: "Personal Grimoire",
    bespoke2_desc: "Handwritten books of shadows bound in fine leather with your name in crimson ink.",
    bespoke3_title: "Unique Talismans",
    bespoke3_desc: "One-of-a-kind pieces created for your journey of enlightenment and power.",
    btn_consultation: "Request Consultation",
    bespoke_note: "Our concierge will contact you within 24 hours",
    guarantee_title: "Sacred Oath Guarantee",
    guarantee_desc: "Every artifact is authenticated by the Grand Council. If your purchase does not meet your expectations within 30 days, we honor a full return — no questions asked. Your trust is our covenant.",
    guarantee1: "Free Worldwide Shipping",
    guarantee2: "Certificate of Authenticity",
    guarantee3: "Discreet Packaging",
    join_headline: "Ascend to the Inner Circle",
    join_subtext: "Those who seek power must prove their worth. Join our exclusive membership and gain access to restricted auctions, VIP previews, and private ceremonies.",
    btn_bespoke: "Request Bespoke Service",
    modal_join_title: "Request Initiation",
    modal_bespoke_title: "Bespoke Consultation",
    label_name: "Full Name",
    label_email: "Email Address",
    label_message: "Message",
    label_vision: "Your Vision",
    btn_submit: "Submit Application",
    modal_join_note: "Your application will be reviewed by the Grand Council",
    modal_bespoke_note: "Our artisans will contact you within 48 hours",
    product7_name: "Baphomet Altar Installation",
    product7_desc: "Ritual Baphomet artifact designed for altar installation. Forged from sacred metals, this powerful invocation object is intended for advanced practitioners of occult arts and high magic ceremonies.",
    product8_name: "Illuminated Tarot Card",
    product8_desc: "Unique illuminated tarot card, adorned with gold leaf gilding and esoteric symbols. An essential divination and spiritual guidance tool for advanced tarot readings.",
    product9_name: "Clairvoyant Crystal Skull",
    product9_desc: "Clairvoyant crystal skull carved from high-grade pure quartz. A deep meditation tool that amplifies inner vision, clairvoyance, and connection to higher planes.",
    product10_name: "Grail Chalice",
    product10_desc: "Ornate Grail Chalice in gilded brass with authentic medieval engravings. A sacred relic used in the holiest ceremonies and spiritual communion rituals.",
    product11_name: "Luck & Attraction Perfums",
    product11_desc: "Vintage Luck & Attraction Perfums, a collection of hand-tinted glass apothecary vials. Perfect vessels for preserving the elixirs, essential oils, and potions of ancient alchemical masters.",
    product12_name: "Baphomet Invocation Box",
    product12_desc: "Baphomet invocation box crafted from carved wood and engraved metal. This ritual case contains sacred sigils and invocation tools for occult ceremonies and connecting with ancient energies."
  },
  es: {
    nav_artifacts: "Artefactos",
    nav_bespoke: "A Medida",
    nav_testimonials: "Testimonios",
    btn_join: "UNIRSE",
    hero_headline: "Artefactos Exclusivos para los Iluminados",
    hero_subtext: "Acceda al conocimiento prohibido, reliquias sagradas y herramientas de ascensión. Reservado exclusivamente para quienes buscan la luz más allá del velo.",
    btn_explore: "Explorar Artefactos",
    btn_request: "Solicitar Iniciación",
    trust_encrypted: "Cifrado",
    trust_members: "Miembros",
    trust_countries: "Países",
    trust_legacy: "Legado",
    section_artifacts: "Artefactos Sagrados",
    section_artifacts_desc: "Cada pieza lleva el peso de los siglos. Forjada por maestros, imbuida de propósito.",
    filter_all: "Todos los Artefactos",
    filter_jewelry: "Joyería",
    filter_manuscripts: "Manuscritos",
    filter_tools: "Herramientas y Reliquias",
    badge_limited: "Limitado",
    badge_rare: "Raro",
    badge_bestseller: "Más Vendido",
    badge_new: "Nuevo",
    badge_sacred: "Sagrado",
    product1_name: "El Colgante Omnisciente",
    product1_desc: "Colgante omnisciente de oro de 24 quilates forjado a mano con geometría sagrada. Una joya esotérica usada por el círculo interno desde el siglo XVIII para la protección y el despertar espiritual.",
    product2_name: "Códice de la Iluminación",
    product2_desc: "Códice de la Iluminación, manuscrito antiguo encuadernado en cuero genuino que contiene 33 grados de sabiduría oculta. Cada página está inscrita a mano para los buscadores de la verdad oculta.",
    product3_name: "Anillo del Sigilo de Poder",
    product3_desc: "Anillo del Sigilo de Poder elaborado en obsidiana y esmalte carmesí. Este sello oculto canaliza las energías antiguas de la Orden y afirma la autoridad espiritual de quien lo lleva.",
    product4_name: "Vela de Oración Ritual",
    product4_desc: "Vela de oración ritual de cera de abeja pura con mecha trenzada. Diseñada para la meditación profunda, la purificación del espacio y la elevación espiritual durante ceremonias sagradas.",
    product5_name: "Sello de Salomón",
    product5_desc: "Sello de Salomón auténtico, libro de impresiones de sellos de cera antiguos. Un grimorio de protección espiritual que contiene los sigilos de los 72 espíritus de la jerarquía.",
    product6_name: "Incienso de Purificación",
    product6_desc: "Incienso de purificación artesanal con resinas naturales de mirra e incienso. Ideal para la limpieza energética, la protección del altar y la armonización de vibraciones durante los rituales.",
    btn_buy: "Comprar Ahora",
    section_testimonials: "Palabras de la Fraternidad",
    testimonial1: '"El colgante cambió la trayectoria de mi vida. Se abrieron puertas que nunca supe que existían."',
    testimonial1_role: "33er Grado • Verificado",
    testimonial2: '"El Códice reveló verdades que ninguna universidad podía enseñar. Cada centavo de la inversión valió la pena."',
    testimonial2_role: "Gran Maestro • Verificado",
    testimonial3: '"Llevo el Anillo del Sigilo a diario. Su presencia impone respeto en cada sala en la que entro."',
    testimonial3_role: "Círculo Interior • Verificado",
    bespoke_badge: "Servicios Fuera del Mercado",
    bespoke_title: "Artefactos y Comisiones a Medida",
    bespoke_desc: "Para quienes buscan piezas más allá de nuestro catálogo. Trabajamos con un círculo selecto de maestros artesanos para crear artefactos personalizados imbuidos con sus sigilos e intenciones personales.",
    bespoke1_title: "Regalia Personalizada",
    bespoke1_desc: "Vestimentas y regalia ceremoniales confeccionadas según sus especificaciones exactas y grado.",
    bespoke2_title: "Grimorio Personal",
    bespoke2_desc: "Libros de sombras escritos a mano, encuadernados en cuero fino con su nombre en tinta carmesí.",
    bespoke3_title: "Talismanes Únicos",
    bespoke3_desc: "Piezas únicas creadas para su viaje de iluminación y poder.",
    btn_consultation: "Solicitar Consulta",
    bespoke_note: "Nuestro concierge se pondrá en contacto en 24 horas",
    guarantee_title: "Garantía del Juramento Sagrado",
    guarantee_desc: "Cada artefacto es autenticado por el Gran Consejo. Si su compra no cumple sus expectativas en 30 días, honramos una devolución completa — sin hacer preguntas. Su confianza es nuestro pacto.",
    guarantee1: "Envío Mundial Gratuito",
    guarantee2: "Certificado de Autenticidad",
    guarantee3: "Embalaje Discreto",
    join_headline: "Ascender al Círculo Interior",
    join_subtext: "Quienes buscan poder deben probar su valía. Únase a nuestra membresía exclusiva y obtenga acceso a subastas restringidas, vistas previas VIP y ceremonias privadas.",
    btn_bespoke: "Solicitar Servicio a Medida",
    modal_join_title: "Solicitar Iniciación",
    modal_bespoke_title: "Consulta a Medida",
    label_name: "Nombre Completo",
    label_email: "Correo Electrónico",
    label_message: "Mensaje",
    label_vision: "Su Visión",
    btn_submit: "Enviar Solicitud",
    modal_join_note: "Su solicitud será revisada por el Gran Consejo",
    modal_bespoke_note: "Nuestros artesanos se pondrán en contacto en 48 horas",
    product7_name: "Instalación de Altar de Baphomet",
    product7_desc: "Artefacto ritual de Baphomet diseñado para instalación en altar. Forjado en metales sagrados, este poderoso objeto de invocación está destinado a practicantes avanzados de las artes ocultas y ceremonias de alta magia.",
    product8_name: "Carta de Tarot Iluminada",
    product8_desc: "Carta de tarot iluminada única, adornada con pan de oro y símbolos esotéricos. Una herramienta esencial de adivinación y guía espiritual para lecturas de tarot avanzadas.",
    product9_name: "Cráneo de Cristal Clarividente",
    product9_desc: "Cráneo de cristal clarividente tallado en cuarzo puro de alta calidad. Una herramienta de meditación profunda que amplifica la visión interior, la clarividencia y la conexión con los planos superiores.",
    product10_name: "Cálice del Grial",
    product10_desc: "Cálice del Grial de aparato en latón dorado con grabados medievales auténticos. Una reliquia sagrada utilizada en las ceremonias más santas y los rituales de comunión espiritual.",
    product11_name: "Frascos de Alquimia",
    product11_desc: "Frascos de alquimia vintage, una colección de frascos de boticario de vidrio teñido a mano. Recipientes perfectos para conservar los elixires, aceites esenciales y pociones de los antiguos maestros alquimistas.",
    product12_name: "Cofre de Invocación de Baphomet",
    product12_desc: "Cofre de invocación de Baphomet tallado en madera y metal grabado. Este estuche ritual contiene sigilos sagrados y herramientas de invocación para ceremonias ocultas y la conexión con energías antiguas."
  },
  de: {
    nav_artifacts: "Artefakte",
    nav_bespoke: "Maßgeschneidert",
    nav_testimonials: "Testimonials",
    btn_join: "BEITRETEN",
    hero_headline: "Exklusive Artefakte für die Erleuchteten",
    hero_subtext: "Zugang zu verbotenem Wissen, heiligen Reliquien und Werkzeugen der Erhebung. Exklusiv für diejenigen, die das Licht jenseits des Schleiers suchen.",
    btn_explore: "Artefakte Erkunden",
    btn_request: "Initiation Beantragen",
    trust_encrypted: "Verschlüsselt",
    trust_members: "Mitglieder",
    trust_countries: "Länder",
    trust_legacy: "Erbe",
    section_artifacts: "Heilige Artefakte",
    section_artifacts_desc: "Jedes Stück trägt das Gewicht der Jahrhunderte. Von Meistern geschaffen, durchdrungen von Zweck.",
    filter_all: "Alle Artefakte",
    filter_jewelry: "Schmuck",
    filter_manuscripts: "Manuskripte",
    filter_tools: "Werkzeuge & Reliquien",
    badge_limited: "Limitiert",
    badge_rare: "Selten",
    badge_bestseller: "Bestseller",
    badge_new: "Neu",
    badge_sacred: "Heilig",
    product1_name: "Der Allsehende Anhänger",
    product1_desc: "Handgeschmiedeter 24-karätiger Goldanhänger mit heiliger Geometrie. Ein esoterisches Schmuckstück, das vom inneren Kreis seit dem 18. Jahrhundert zum Schutz und zur spirituellen Erweckung getragen wird.",
    product2_name: "Kodex der Erleuchtung",
    product2_desc: "Kodex der Erleuchtung, eine antike, in echtes Leder gebundene Handschrift mit 33 Graden verborgener Weisheit. Jede Seite ist für Sucher der okkulten Wahrheit von Hand beschrieben.",
    product3_name: "Siegelring der Macht",
    product3_desc: "Siegelring der Macht aus Obsidian und karmesinrotem Emaille. Dieser okkulte Siegelring kanalisiert die uralten Energien des Ordens und bekräftigt die spirituelle Autorität seines Trägers.",
    product4_name: "Rituelle Gebetskerze",
    product4_desc: "Rituelle Gebetskerze aus reinem Bienenwachs mit geflochtenem Docht. Entwickelt für tiefe Meditation, Raumreinigung und spirituelle Erhebung während heiliger Zeremonien.",
    product5_name: "Siegel Salomos",
    product5_desc: "Authentisches Siegel Salomos, ein antikes Wachssiegel-Abdruckbuch. Ein Grimorium des spirituellen Schutzes, das die Sigillen der 72 Geister der Hierarchie enthält.",
    product6_name: "Reinigungs-Räucherwerk",
    product6_desc: "Handgemachtes Reinigungs-Räucherwerk mit natürlichen Myrrhen- und Weihrauchharzen. Ideal zur Energiereinigung, zum Altarschutz und zur Harmonisierung von Schwingungen bei Ritualen.",
    btn_buy: "Jetzt Kaufen",
    section_testimonials: "Worte der Bruderschaft",
    testimonial1: '"Der Anhänger veränderte den Verlauf meines Lebens. Türen öffneten sich, von denen ich nie wusste, dass sie existierten."',
    testimonial1_role: "33. Grad • Verifiziert",
    testimonial2: '"Der Kodex enthüllte Wahrheiten, die keine Universität lehren konnte. Jeder Cent der Investition war es wert."',
    testimonial2_role: "Großmeister • Verifiziert",
    testimonial3: '"Ich trage den Siegelring täglich. Seine Präsenz gebietet Respekt in jedem Raum, den ich betrete."',
    testimonial3_role: "Innerer Kreis • Verifiziert",
    bespoke_badge: "Außerhalb des Marktes",
    bespoke_title: "Maßgeschneiderte Artefakte & Aufträge",
    bespoke_desc: "Für diejenigen, die nach Stücken jenseits unseres Katalogs suchen. Wir arbeiten mit einem ausgewählten Kreis von Meisterhandwerkern, um maßgeschneiderte Artefakte zu schaffen, die mit Ihren persönlichen Sigillen und Absichten durchtränkt sind.",
    bespoke1_title: "Maßgeschneiderte Regalia",
    bespoke1_desc: "Zeremonielle Gewänder und Regalia, die nach Ihren genauen Spezifikationen und Ihrem Grad gefertigt werden.",
    bespoke2_title: "Persönliches Grimoire",
    bespoke2_desc: "Handgeschriebene Schattenbücher, gebunden in feinem Leder mit Ihrem Namen in karmesinroter Tinte.",
    bespoke3_title: "Einzigartige Talismane",
    bespoke3_desc: "Einzigartige Stücke, die für Ihre Reise der Erleuchtung und Macht geschaffen wurden.",
    btn_consultation: "Beratung Anfordern",
    bespoke_note: "Unser Concierge wird sich innerhalb von 24 Stunden bei Ihnen melden",
    guarantee_title: "Garantie des Heiligen Eides",
    guarantee_desc: "Jedes Artefakt wird vom Großen Rat authentifiziert. Wenn Ihr Kauf Ihre Erwartungen innerhalb von 30 Tagen nicht erfüllt, ehren wir eine vollständige Rückgabe — ohne Fragen. Ihr Vertrauen ist unser Bündnis.",
    guarantee1: "Kostenloser Weltweiter Versand",
    guarantee2: "Echtheitszertifikat",
    guarantee3: "Diskrete Verpackung",
    join_headline: "Zum Inneren Kreis Aufsteigen",
    join_subtext: "Diejenigen, die Macht suchen, müssen ihren Wert beweisen. Treten Sie unserer exklusiven Mitgliedschaft bei und erhalten Sie Zugang zu eingeschränkten Auktionen, VIP-Vorschauen und privaten Zeremonien.",
    btn_bespoke: "Maßgeschneiderten Service Anfordern",
    modal_join_title: "Initiation Beantragen",
    modal_bespoke_title: "Maßgeschneiderte Beratung",
    label_name: "Vollständiger Name",
    label_email: "E-Mail-Adresse",
    label_message: "Nachricht",
    label_vision: "Ihre Vision",
    btn_submit: "Bewerbung Einreichen",
    modal_join_note: "Ihre Bewerbung wird vom Großen Rat geprüft",
    modal_bespoke_note: "Unsere Handwerker werden sich innerhalb von 48 Stunden bei Ihnen melden",
    product7_name: "Baphomet Altar-Installation",
    product7_desc: "Rituelles Baphomet-Artefakt für die Altar-Installation. Aus heiligen Metallen geschmiedet, ist dieses mächtige Invokationsobjekt für fortgeschrittene Praktizierende der okkulten Künste und Hochmagie-Zeremonien bestimmt.",
    product8_name: "Illuminierte Tarotkarte",
    product8_desc: "Einzigartige illuminierte Tarotkarte, verziert mit Blattgold und esoterischen Symbolen. Ein wesentliches Werkzeug für Wahrsagerei und spirituelle Führung bei fortgeschrittenen Tarot-Legungen.",
    product9_name: "Hellseherischer Kristallschädel",
    product9_desc: "Hellseherischer Kristallschädel, geschnitzt aus hochwertigem reinem Quarz. Ein Werkzeug für tiefe Meditation, das die innere Vision, Hellseherei und die Verbindung zu höheren Ebenen verstärkt.",
    product10_name: "Gral-Kelch",
    product10_desc: "Prächtiger Gral-Kelch aus vergoldetem Messing mit authentischen mittelalterlichen Gravuren. Eine heilige Reliquie, die bei den heiligsten Zeremonien und spirituellen Kommunionritualen verwendet wird.",
    product11_name: "Alchemie-Flakons",
    product11_desc: "Vintage Alchemie-Flakons, eine Sammlung handgetönter Apothekerflakons aus Glas. Perfekte Gefäße zur Aufbewahrung der Elixiere, ätherischen Öle und Tränke alter alchemistischer Meister.",
    product12_name: "Baphomet-Invokationskasten",
    product12_desc: "Baphomet-Invokationskasten aus geschnitztem Holz und graviertem Metall. Dieser rituelle Behälter enthält heilige Sigillen und Invokationswerkzeuge für okkulte Zeremonien und die Verbindung zu uralten Energien."
  },
  pt: {
    nav_artifacts: "Artefatos",
    nav_bespoke: "Sob Medida",
    nav_testimonials: "Depoimentos",
    btn_join: "JUNTAR-SE",
    hero_headline: "Artefatos Exclusivos para os Iluminados",
    hero_subtext: "Acesso ao conhecimento proibido, relíquias sagradas e ferramentas de ascensão. Reservado exclusivamente para aqueles que buscam a luz além do véu.",
    btn_explore: "Explorar Artefatos",
    btn_request: "Solicitar Iniciação",
    trust_encrypted: "Criptografado",
    trust_members: "Membros",
    trust_countries: "Países",
    trust_legacy: "Legado",
    section_artifacts: "Artefatos Sagrados",
    section_artifacts_desc: "Cada peça carrega o peso dos séculos. Forjada por mestres, imbuída de propósito.",
    filter_all: "Todos os Artefatos",
    filter_jewelry: "Joias",
    filter_manuscripts: "Manuscritos",
    filter_tools: "Ferramentas & Relíquias",
    badge_limited: "Limitado",
    badge_rare: "Raro",
    badge_bestseller: "Mais Vendido",
    badge_new: "Novo",
    badge_sacred: "Sagrado",
    product1_name: "O Pingente Onisciente",
    product1_desc: "Pingente onisciente de ouro 24k forjado à mão com geometria sagrada. Uma joia esotérica usada pelo círculo interno desde o século XVIII para proteção e despertar espiritual.",
    product2_name: "Códice da Iluminação",
    product2_desc: "Códice da Iluminação, manuscrito antigo encadernado em couro genuíno contendo 33 graus de sabedoria oculta. Cada página é inscrita à mão para os buscadores da verdade oculta.",
    product3_name: "Anel do Sigilo de Poder",
    product3_desc: "Anel do Sigilo de Poder elaborado em obsidiana e esmalte carmim. Este sinete oculto canaliza as energias antigas da Ordem e afirma a autoridade espiritual de quem o usa.",
    product4_name: "Vela de Oração Ritual",
    product4_desc: "Vela de oração ritual de cera de abelha pura com pavio trançado. Projetada para meditação profunda, purificação do espaço e elevação espiritual durante cerimônias sagradas.",
    product5_name: "Selo de Salomão",
    product5_desc: "Selo de Salomão autêntico, livro de impressões de selos de cera antigos. Um grimório de proteção espiritual contendo os sigilos dos 72 espíritos da hierarquia.",
    product6_name: "Incenso de Purificação",
    product6_desc: "Incenso de purificação artesanal com resinas naturais de mirra e olíbano. Ideal para limpeza energética, proteção do altar e harmonização de vibrações durante rituais.",
    btn_buy: "Comprar Agora",
    section_testimonials: "Palavras da Fraternidade",
    testimonial1: '"O pingente mudou a trajetória da minha vida. Portas se abriram que eu nunca soube que existiam."',
    testimonial1_role: "33º Grau • Verificado",
    testimonial2: '"O Códice revelou verdades que nenhuma universidade poderia ensinar. Cada centavo do investimento valeu a pena."',
    testimonial2_role: "Grão-Mestre • Verificado",
    testimonial3: '"Eu uso o Anel do Sigilo diariamente. Sua presença impõe respeito em cada sala que eu entro."',
    testimonial3_role: "Círculo Interno • Verificado",
    bespoke_badge: "Serviços Fora do Mercado",
    bespoke_title: "Artefatos & Comissões Sob Medida",
    bespoke_desc: "Para aqueles que buscam peças além do nosso catálogo. Trabalhamos com um círculo selecionado de mestres artesãos para criar artefatos personalizados imbuídos com seus sigilos e intenções pessoais.",
    bespoke1_title: "Regalia Personalizada",
    bespoke1_desc: "Vestimentas e regalia cerimoniais confeccionadas de acordo com suas especificações exatas e grau.",
    bespoke2_title: "Grimório Pessoal",
    bespoke2_desc: "Livros de sombras escritos à mão, encadernados em couro fino com seu nome em tinta carmim.",
    bespoke3_title: "Talismãs Únicos",
    bespoke3_desc: "Peças únicas criadas para sua jornada de iluminação e poder.",
    btn_consultation: "Solicitar Consulta",
    bespoke_note: "Nosso concierge entrará em contato em 24 horas",
    guarantee_title: "Garantia do Juramento Sagrado",
    guarantee_desc: "Cada artefato é autenticado pelo Grande Conselho. Se sua compra não atender suas expectativas em 30 dias, honramos uma devolução completa — sem perguntas. Sua confiança é nossa aliança.",
    guarantee1: "Envio Mundial Gratuito",
    guarantee2: "Certificado de Autenticidade",
    guarantee3: "Embalagem Discreta",
    join_headline: "Ascender ao Círculo Interno",
    join_subtext: "Aqueles que buscam poder devem provar seu valor. Junte-se à nossa associação exclusiva e obtenha acesso a leilões restritos, prévias VIP e cerimônias privadas.",
    btn_bespoke: "Solicitar Serviço Sob Medida",
    modal_join_title: "Solicitar Iniciação",
    modal_bespoke_title: "Consulta Sob Medida",
    label_name: "Nome Completo",
    label_email: "Endereço de Email",
    label_message: "Mensagem",
    label_vision: "Sua Visão",
    btn_submit: "Enviar Solicitação",
    modal_join_note: "Sua candidatura será revisada pelo Grande Conselho",
    modal_bespoke_note: "Nossos artesãos entrarão em contato em 48 horas",
    product7_name: "Instalação de Altar de Baphomet",
    product7_desc: "Artefato ritual de Baphomet projetado para instalação em altar. Forjado em metais sagrados, este poderoso objeto de invocação é destinado a praticantes avançados das artes ocultas e cerimônias de alta magia.",
    product8_name: "Carta de Tarô Iluminada",
    product8_desc: "Carta de tarô iluminada única, adornada com folha de ouro e símbolos esotéricos. Uma ferramenta essencial de adivinhação e orientação espiritual para leituras de tarô avançadas.",
    product9_name: "Caveira de Cristal Clarividente",
    product9_desc: "Caveira de cristal clarividente esculpida em quartzo puro de alta qualidade. Uma ferramenta de meditação profunda que amplifica a visão interior, a clarividência e a conexão com planos superiores.",
    product10_name: "Cálice do Graal",
    product10_desc: "Cálice do Graal de aparato em latão dourado com gravuras medievais autênticas. Uma relíquia sagrada usada nas cerimônias mais santas e nos rituais de comunhão espiritual.",
    product11_name: "Frascos de Alquimia",
    product11_desc: "Frascos de alquimia vintage, uma coleção de frascos de boticário de vidro tingido à mão. Recipientes perfeitos para conservar os elixires, óleos essenciais e poções dos antigos mestres alquimistas.",
    product12_name: "Caixa de Invocação de Baphomet",
    product12_desc: "Caixa de invocação de Baphomet em madeira esculpida e metal gravado. Este estojo ritual contém sigilos sagrados e ferramentas de invocação para cerimônias ocultas e conexão com energias antigas."
  },
  ar: {
    nav_artifacts: "القطع الأثرية",
    nav_bespoke: "حسب الطلب",
    nav_testimonials: "الشهادات",
    btn_join: "انضم إلينا",
    hero_headline: "قطع أثرية حصرية للمستنيرين",
    hero_subtext: "الوصول إلى المعرفة المحرمة والآثار المقدسة وأدوات التصعيد. محفوظة حصريًا لأولئك الذين يسعون إلى النور ما وراء الحجاب.",
    btn_explore: "استكشف القطع الأثرية",
    btn_request: "طلب التهيئة",
    trust_encrypted: "مشفّر",
    trust_members: "أعضاء",
    trust_countries: "دول",
    trust_legacy: "إرث",
    section_artifacts: "الآثار المقدسة",
    section_artifacts_desc: "كل قطعة تحمل ثقل القرون. صُنعت بأيدي الأساتذة، مشحونة بالغرض.",
    filter_all: "جميع القطع الأثرية",
    filter_jewelry: "المجوهرات",
    filter_manuscripts: "المخطوطات",
    filter_tools: "الأدوات والآثار",
    badge_limited: "محدود",
    badge_rare: "نادر",
    badge_bestseller: "الأكثر مبيعًا",
    badge_new: "جديد",
    badge_sacred: "مقدس",
    product1_name: "قلادة العين الشاملة",
    product1_desc: "قلادة العين الشاملة من الذهب عيار 24 قيراطًا مُشكّلة يدويًا مع الهندسة المقدسة. جوهرة باطنية ارتداها الدائرة الداخلية منذ القرن الثامن عشر للحماية والصحوة الروحية.",
    product2_name: "كوديكس التنوير",
    product2_desc: "كوديكس التنوير، مخطوطة قديمة مُجلّدة بجلد أصلي تحتوي على 33 درجة من الحكمة الخفية. كل صفحة مكتوبة باليد لباحثي الحقيقة الباطنية.",
    product3_name: "خاتم ختم القوة",
    product3_desc: "خاتم ختم القوة مصنوع من الأوبسيديان والمينا القرمزي. هذا الختم الباطني يوجّه طاقات النظام القديمة ويؤكد السلطة الروحية لمن يرتديه.",
    product4_name: "شمعة صلاة طقسية",
    product4_desc: "شمعة صلاة طقسية مصنوعة من شمع العسل النقي بفتيل مضفر. مصممة للتأمل العميق، وتنقية المساحة، والارتقاء الروحي خلال الطقوس المقدسة.",
    product5_name: "ختم سليمان",
    product5_desc: "ختم سليمان الأصيل، كتاب طبعات ختم شمع قديم. كتاب تعاويذ للحماية الروحية يحتوي على رموز 72 روحًا من التسلسل الهرمي.",
    product6_name: "بخور التنقية",
    product6_desc: "بخور تنقية يدوي الصنع براتنجات المُر واللبان الطبيعية. مثالي لتنظيف الطاقة، وحماية المذبح، وموازنة الاهتزازات أثناء الطقوس.",
    btn_buy: "اشتري الآن",
    section_testimonials: "كلمات من الأخوية",
    testimonial1: '"غيّرت القلادة مسار حياتي. فُتحت أبواب لم أكن أعرف بوجودها."',
    testimonial1_role: "الدرجة 33 • موثّق",
    testimonial2: '"كشف الكوديكس حقائق لا جامعة تستطيع تعليمها. كل سنت من الاستثمار كان يستحق."',
    testimonial2_role: "السيد الأكبر • موثّق",
    testimonial3: '"أرتدي خاتم الختم يوميًا. حضوره يفرض الاحترام في كل غرفة أدخلها."',
    testimonial3_role: "الدائرة الداخلية • موثّق",
    bespoke_badge: "خدمات خارج السوق",
    bespoke_title: "قطع أثرية وطلبات حسب الطلب",
    bespoke_desc: "لأولئك الذين يبحثون عن قطع أخرى من كتالوجنا. نعمل مع دائرة مختارة من الحرفيين المتميزين لإنشاء قطع أثرية مخصصة مشحونة بأختامك ونواياك الشخصية.",
    bespoke1_title: "زي طقسي مخصص",
    bespoke1_desc: "ملابس ومجوهرات طقسية مصنوعة وفقًا لمواصفاتك الدقيقة ودرجتك.",
    bespoke2_title: "كتاب سحر شخصي",
    bespoke2_desc: "كتب سحر مكتوبة باليد، مُجلّدة بجلد فاخر مع اسمك بحبر قرمزي.",
    bespoke3_title: "تمائم فريدة",
    bespoke3_desc: "قطع فريدة من نوعها تم إنشاؤها لرحلتك نحو التنوير والقوة.",
    btn_consultation: "طلب استشارة",
    bespoke_note: "سيتواصل معك موظف الاستقبال خلال 24 ساعة",
    guarantee_title: "ضمان العهد المقدس",
    guarantee_desc: "كل قطعة أثرية يتم التحقق من أصالتها من قبل المجلس الأكبر. إذا لم يكن شراؤك على قدر توقعاتك خلال 30 يومًا، نحن نكرم الإرجاع الكامل — دون أسئلة. ثقتك هي عهدنا.",
    guarantee1: "شحن مجاني عالمي",
    guarantee2: "شهادة أصالة",
    guarantee3: "تغليف مخفي",
    join_headline: "صعد إلى الدائرة الداخلية",
    join_subtext: "يجب على أولئك الذين يسعون إلى القوة إثبات جدارتهم. انضم إلى عضويتنا الحصرية واحصل على حق الوصول إلى المزادات المقيدة والمعاينات VIP والطقوس الخاصة.",
    btn_bespoke: "طلب خدمة حسب الطلب",
    modal_join_title: "طلب التهيئة",
    modal_bespoke_title: "استشارة حسب الطلب",
    label_name: "الاسم الكامل",
    label_email: "عنوان البريد الإلكتروني",
    label_message: "الرسالة",
    label_vision: "رؤيتك",
    btn_submit: "إرسال الطلب",
    modal_join_note: "سيتم مراجعة طلبك من قبل المجلس الأكبر",
    modal_bespoke_note: "سيتواصل حرفيونا معك خلال 48 ساعة",
    product7_name: "تركيب مذبح بافوميت",
    product7_desc: "قطعة أثرية طقسية لبافوميت مصممة للتركيب على المذبح. مصنوعة من معادن مقدسة، هذا الكائن القوي للاستدعاء مخصص للممارسين المتقدمين للفنون الخفية وطقوس السحر العالي.",
    product8_name: "بطاقة تاروت مضيئة",
    product8_desc: "بطاقة تاروت مضيئة فريدة، مزينة بطلاء ورق الذهب والرموز الباطنية. أداة أساسية للعرافة والإرشاد الروحي لقراءات التاروت المتقدمة.",
    product9_name: "جمجمة الكريستال المتنبئة",
    product9_desc: "جمجمة كريستال متنبئة منحوتة من الكوارتز النقي عالي الجودة. أداة تأمل عميق تُضخّم الرؤية الداخلية، والاستبصار، والاتصال بالمستويات العليا.",
    product10_name: "كأس الجرال",
    product10_desc: "كأس الجرال الاحتفالي من النحاس المطلي بالذهب مع نقوش قروسطية أصيلة. أثر مقدس يُستخدم في أقدس الطقوس وطقوس communion الروحية.",
    product11_name: "قارورات الخيمياء",
    product11_desc: "قارورات خيمياء عتيقة، مجموعة من قوارير الصيدلية الزجاجية الملونة يدويًا. أوعية مثالية لحفظ إكسيرات، وزيوت أساسية، وجرعات الأساتذة الخيميائيين القدماء.",
    product12_name: "صندوق استدعاء بافوميت",
    product12_desc: "صندوق استدعاء بافوميت مصنوع من الخشب المنحوت والمعدن المحفور. تحتوي هذه العلبة الطقسية على ختم مقدس وأدوات استدعاء للطقوس الخفية والاتصال بالطاقات القديمة."
  }
};

    let currentLang = 'fr';

    function changeLanguage(lang) {
      currentLang = lang;
      document.documentElement.lang = lang;

      // Update RTL for Arabic
      if (lang === 'ar') {
        document.body.setAttribute('dir', 'rtl');
      } else {
        document.body.setAttribute('dir', 'ltr');
      }

      // Update all elements with data-i18n attribute
      const elements = document.querySelectorAll('[data-i18n]');
      elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
          el.textContent = translations[lang][key];
        }
      });

      // Update select values
      document.getElementById('lang-selector').value = lang;
      const mobileSelect = document.getElementById('lang-selector-mobile');
      if (mobileSelect) mobileSelect.value = lang;

      // Re-render Lucide icons
      lucide.createIcons();
    }

    // Initialize with French
    document.addEventListener('DOMContentLoaded', function() {
      changeLanguage('fr');
    });

    lucide.createIcons();

    const defaultConfig = {
      site_title: 'THE ORDER',
      hero_headline: 'Exclusive Artifacts for the Enlightened',
      hero_subtext: 'Access forbidden knowledge, sacred relics, and tools of ascension. Reserved exclusively for those who seek the light beyond the veil.',
      join_headline: 'Ascend to the Inner Circle',
      join_subtext: 'Those who seek power must prove their worth. Join our exclusive membership and gain access to restricted auctions, VIP previews, and private ceremonies.',
      background_color: '#0a0a0f',
      surface_color: '#0d1b3e',
      text_color: '#f5f0e8',
      primary_action_color: '#dc143c',
      secondary_action_color: '#8b0000',
      font_family: 'Cormorant Garamond',
      font_size: 16
    };

    function applyConfig(config) {
      const c = { ...defaultConfig, ...config };
      document.getElementById('nav-title').textContent = c.site_title;
      document.getElementById('hero-headline').textContent = c.hero_headline;
      document.getElementById('hero-subtext').textContent = c.hero_subtext;
      document.getElementById('join-headline').textContent = c.join_headline;
      document.getElementById('join-subtext').textContent = c.join_subtext;
      document.body.style.fontFamily = `${c.font_family}, serif`;
    }

    window.elementSdk.init({
      defaultConfig,
      onConfigChange: async (config) => { applyConfig(config); },
      mapToCapabilities: (config) => ({
        recolorables: [
          { get: () => config.background_color || defaultConfig.background_color, set: (v) => { config.background_color = v; window.elementSdk.setConfig({ background_color: v }); } },
          { get: () => config.surface_color || defaultConfig.surface_color, set: (v) => { config.surface_color = v; window.elementSdk.setConfig({ surface_color: v }); } },
          { get: () => config.text_color || defaultConfig.text_color, set: (v) => { config.text_color = v; window.elementSdk.setConfig({ text_color: v }); } },
          { get: () => config.primary_action_color || defaultConfig.primary_action_color, set: (v) => { config.primary_action_color = v; window.elementSdk.setConfig({ primary_action_color: v }); } },
          { get: () => config.secondary_action_color || defaultConfig.secondary_action_color, set: (v) => { config.secondary_action_color = v; window.elementSdk.setConfig({ secondary_action_color: v }); } }
        ],
        borderables: [],
        fontEditable: {
          get: () => config.font_family || defaultConfig.font_family,
          set: (v) => { config.font_family = v; window.elementSdk.setConfig({ font_family: v }); }
        },
        fontSizeable: {
          get: () => config.font_size || defaultConfig.font_size,
          set: (v) => { config.font_size = v; window.elementSdk.setConfig({ font_size: v }); }
        }
      }),
      mapToEditPanelValues: (config) => new Map([
        ['site_title', config.site_title || defaultConfig.site_title],
        ['hero_headline', config.hero_headline || defaultConfig.hero_headline],
        ['hero_subtext', config.hero_subtext || defaultConfig.hero_subtext],
        ['join_headline', config.join_headline || defaultConfig.join_headline],
        ['join_subtext', config.join_subtext || defaultConfig.join_subtext]
      ])
    });

    applyConfig(defaultConfig);

    // Filter functionality
    function filterProducts(category) {
      const products = document.querySelectorAll('.product');
      const buttons = document.querySelectorAll('.filter-btn');

      buttons.forEach(btn => btn.classList.remove('active'));
      event.target.classList.add('active');

      products.forEach(product => {
        if (category === 'all' || product.classList.contains(category)) {
          product.style.display = 'block';
          setTimeout(() => product.style.opacity = '1', 10);
        } else {
          product.style.opacity = '0';
          setTimeout(() => product.style.display = 'none', 300);
        }
      });
    }

    // Form handlers
    function handleJoinSubmit(e) {
      e.preventDefault();
      const messages = {
        fr: '✓ Candidature soumise. Le Grand Conseil examinera votre demande.',
        en: '✓ Application submitted. The Grand Council will review your request.',
        es: '✓ Solicitud enviada. El Gran Consejo revisará su solicitud.',
        de: '✓ Bewerbung eingereicht. Der Große Rat wird Ihre Anfrage prüfen.',
        pt: '✓ Candidatura enviada. O Grande Conselho revisará sua solicitação.',
        ar: '✓ تم إرسال الطلب. سيراجع المجلس الأكبر طلبك.'
      };
      alert(messages[currentLang] || messages['en']);
      document.getElementById('join-modal').classList.add('hidden');
      e.target.reset();
    }

    function handleBespokeSubmit(e) {
      e.preventDefault();
      const messages = {
        fr: '✓ Demande de consultation envoyée. Nos artisans vous contacteront sous peu.',
        en: '✓ Consultation request sent. Our artisans will contact you shortly.',
        es: '✓ Solicitud de consulta enviada. Nuestros artesanos se pondrán en contacto pronto.',
        de: '✓ Beratungsanfrage gesendet. Unsere Handwerker werden sich in Kürze bei Ihnen melden.',
        pt: '✓ Solicitação de consulta enviada. Nossos artesãos entrarão em contato em breve.',
        ar: '✓ تم إرسال طلب الاستشارة. سيتواصل حرفيونا معك قريبًا.'
      };
      alert(messages[currentLang] || messages['en']);
      document.getElementById('bespoke-modal').classList.add('hidden');
      e.target.reset();
    }